# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vasily/Projects/opencv_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vasily/Projects/opencv_cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vasily/Projects/opencv_cpp/CMakeFiles /home/vasily/Projects/opencv_cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vasily/Projects/opencv_cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named optical_2

# Build rule for target.
optical_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optical_2
.PHONY : optical_2

# fast build rule for target.
optical_2/fast:
	$(MAKE) -f CMakeFiles/optical_2.dir/build.make CMakeFiles/optical_2.dir/build
.PHONY : optical_2/fast

#=============================================================================
# Target rules for targets named aruco_board

# Build rule for target.
aruco_board: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aruco_board
.PHONY : aruco_board

# fast build rule for target.
aruco_board/fast:
	$(MAKE) -f CMakeFiles/aruco_board.dir/build.make CMakeFiles/aruco_board.dir/build
.PHONY : aruco_board/fast

#=============================================================================
# Target rules for targets named aruco

# Build rule for target.
aruco: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aruco
.PHONY : aruco

# fast build rule for target.
aruco/fast:
	$(MAKE) -f CMakeFiles/aruco.dir/build.make CMakeFiles/aruco.dir/build
.PHONY : aruco/fast

aruco.o: aruco.cpp.o

.PHONY : aruco.o

# target to build an object file
aruco.cpp.o:
	$(MAKE) -f CMakeFiles/aruco.dir/build.make CMakeFiles/aruco.dir/aruco.cpp.o
.PHONY : aruco.cpp.o

aruco.i: aruco.cpp.i

.PHONY : aruco.i

# target to preprocess a source file
aruco.cpp.i:
	$(MAKE) -f CMakeFiles/aruco.dir/build.make CMakeFiles/aruco.dir/aruco.cpp.i
.PHONY : aruco.cpp.i

aruco.s: aruco.cpp.s

.PHONY : aruco.s

# target to generate assembly for a file
aruco.cpp.s:
	$(MAKE) -f CMakeFiles/aruco.dir/build.make CMakeFiles/aruco.dir/aruco.cpp.s
.PHONY : aruco.cpp.s

aruco_board.o: aruco_board.cpp.o

.PHONY : aruco_board.o

# target to build an object file
aruco_board.cpp.o:
	$(MAKE) -f CMakeFiles/aruco_board.dir/build.make CMakeFiles/aruco_board.dir/aruco_board.cpp.o
.PHONY : aruco_board.cpp.o

aruco_board.i: aruco_board.cpp.i

.PHONY : aruco_board.i

# target to preprocess a source file
aruco_board.cpp.i:
	$(MAKE) -f CMakeFiles/aruco_board.dir/build.make CMakeFiles/aruco_board.dir/aruco_board.cpp.i
.PHONY : aruco_board.cpp.i

aruco_board.s: aruco_board.cpp.s

.PHONY : aruco_board.s

# target to generate assembly for a file
aruco_board.cpp.s:
	$(MAKE) -f CMakeFiles/aruco_board.dir/build.make CMakeFiles/aruco_board.dir/aruco_board.cpp.s
.PHONY : aruco_board.cpp.s

optical_flow.o: optical_flow.cpp.o

.PHONY : optical_flow.o

# target to build an object file
optical_flow.cpp.o:
	$(MAKE) -f CMakeFiles/optical_2.dir/build.make CMakeFiles/optical_2.dir/optical_flow.cpp.o
.PHONY : optical_flow.cpp.o

optical_flow.i: optical_flow.cpp.i

.PHONY : optical_flow.i

# target to preprocess a source file
optical_flow.cpp.i:
	$(MAKE) -f CMakeFiles/optical_2.dir/build.make CMakeFiles/optical_2.dir/optical_flow.cpp.i
.PHONY : optical_flow.cpp.i

optical_flow.s: optical_flow.cpp.s

.PHONY : optical_flow.s

# target to generate assembly for a file
optical_flow.cpp.s:
	$(MAKE) -f CMakeFiles/optical_2.dir/build.make CMakeFiles/optical_2.dir/optical_flow.cpp.s
.PHONY : optical_flow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... optical_2"
	@echo "... aruco_board"
	@echo "... aruco"
	@echo "... aruco.o"
	@echo "... aruco.i"
	@echo "... aruco.s"
	@echo "... aruco_board.o"
	@echo "... aruco_board.i"
	@echo "... aruco_board.s"
	@echo "... optical_flow.o"
	@echo "... optical_flow.i"
	@echo "... optical_flow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

